### ISSUE TITLE
Is there any way to use this? 

### ISSUE THREAD

**Issue by Nevos08** [BTNGaming/gcphone#3]
Is it possbible to use this phone? There is no release to download

**Comment by BTNGaming** [comment]
You click the big green button that says CODE and click Download Zip
But don't use this. Go to https://github.com/BTNGaming/Re-Ignited-Phone and download that one. Just released it today.

If you want constant updates, read the Re-Ignited-Phone version of GCPhones README file for our discord. Comes with a full installation tutorial as well.
